### ISSUE TITLE
Node issue on windows

### ISSUE THREAD

**Issue by vidjuheffex** [scottaj/mocha.el#51]
```
-*- mode: mocha-compilation; default-directory: "~/TIY/projects/snippets/" -*-
Mocha started at Fri Jul 14 00:58:29

NODE_ENV=test C:\Program Files\nodejs\node.exe node_modules/.bin/mocha.cmd --recursive --reporter dot -t 5000 --reporter spec 
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

Mocha exited abnormally with code 1 at Fri Jul 14 00:58:29
```

all configured with customize-group

**Comment by vidjuheffex** [comment]
I deleted all customizations and tried just running it.
I got:
```
-*- mode: mocha-compilation; default-directory: "~/TIY/projects/snippets/" -*-
Mocha started at Fri Jul 14 01:03:49

 node node_modules/.bin/mocha --recursive --reporter dot 
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\Julian\TIY\projects\snippets\node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

Mocha exited abnormally with code 1 at Fri Jul 14 01:03:50
```

which I now realize is a duplicate of  #38

**Comment by felipeochoa** [comment]
Closing as duplicate
